# Generated by Django 6.0.1 on 2026-01-31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Wallet', max_length=256)),
                ('entropy', models.CharField(max_length=256)),
                ('passphrase', models.CharField(blank=True, max_length=256)),
                ('evr_liquidity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('last_balance_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('wif', models.CharField(max_length=256)),
                ('account', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField()),
                ('is_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='Wallet.userwallet')),
            ],
        ),
    ]
