# Generated by Django 6.0.1 on 2026-01-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_userwallet_name_alter_userwallet_passphrase_and_more'),
    ]

    operations = [
    ]
