# Generated by Django 6.0.1 on 2026-01-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_userwallet_evr_liquidity_and_more'),
    ]

    operations = [
    ]
