# Generated by Django 6.0.1 on 2026-02-02 00:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_remove_userwallet_id_userwallet_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('main', 'Main'), ('sub', 'Sub'), ('unique', 'Unique'), ('messaging_channel', 'Messaging Channel'), ('qualifier', 'Qualifier'), ('sub_qualifier', 'Sub Qualifier'), ('restricted', 'Restricted'), ('administrator', 'Administrator')], default='main', max_length=32)),
                ('total_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedAssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='Wallet.trackedasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asset', 'user')},
            },
        ),
    ]
