# Generated by Django 6.0.1 on 2026-02-09 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_alter_trackedasset_id_alter_trackedassetholding_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFSUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_stored_on_ipfs', models.FileField(blank=True, null=True, upload_to='')),
                ('ipfs_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipfs_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
