# Generated by Django 6.0.1 on 2026-02-10 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0007_ipfsupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedasset',
            name='has_toll',
            field=models.BooleanField(default=False, help_text='Whether asset has transfer toll enabled'),
        ),
        migrations.AddField(
            model_name='trackedasset',
            name='ipfs_hash',
            field=models.CharField(blank=True, help_text='IPFS hash for asset metadata', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackedasset',
            name='is_reissuable',
            field=models.BooleanField(default=True, help_text='Whether asset can be reissued'),
        ),
        migrations.AddField(
            model_name='trackedasset',
            name='toll_address',
            field=models.CharField(blank=True, help_text='Address receiving toll payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackedasset',
            name='toll_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Toll percentage for transfers', max_digits=5),
        ),
        migrations.AddField(
            model_name='trackedasset',
            name='units',
            field=models.IntegerField(default=0, help_text='Decimal places for asset divisibility (0-8)'),
        ),
        migrations.AlterField(
            model_name='trackedasset',
            name='asset_type',
            field=models.CharField(choices=[('main', 'Main'), ('sub', 'Sub'), ('unique', 'Unique'), ('messaging_channel', 'Messaging Channel'), ('qualifier', 'Qualifier'), ('sub_qualifier', 'Sub Qualifier'), ('restricted', 'Restricted'), ('administrator', 'Administrator'), ('nft', 'NFT'), ('vault', 'Vault')], default='main', max_length=32),
        ),
    ]
