# Generated by Django 6.0.1 on 2026-02-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0008_trackedasset_has_toll_trackedasset_ipfs_hash_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPFSUpload',
        ),
    ]
