# Generated by Django 6.0.1 on 2026-08-05 21:17

from decimal import Decimal
from django.db import migrations, models


def backfill_mainnet_wallet_balances(apps, schema_editor):
    UserWallet = apps.get_model('Wallet', 'UserWallet')
    for wallet in UserWallet.objects.all().iterator():
        wallet.evr_liquidity_mainnet = wallet.evr_liquidity
        wallet.last_balance_update_mainnet = wallet.last_balance_update
        wallet.save(update_fields=['evr_liquidity_mainnet', 'last_balance_update_mainnet'])


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0010_safetradecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='evr_liquidity_mainnet',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='evr_liquidity_testnet',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='last_balance_update_mainnet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='last_balance_update_testnet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='network_mode',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='walletaddress',
            unique_together={('wallet', 'network_mode', 'account', 'index', 'is_change')},
        ),
        migrations.RunPython(backfill_mainnet_wallet_balances, migrations.RunPython.noop),
    ]
