# Generated by Django 6.0.1 on 2026-02-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidityContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contract name', max_length=255)),
                ('contract_address', models.CharField(help_text='Evrmore asset name or contract identifier', max_length=255, unique=True)),
                ('source_code', models.TextField(blank=True, help_text='Solidity source code')),
                ('bytecode', models.TextField(blank=True, help_text='Compiled bytecode')),
                ('abi', models.JSONField(default=list, help_text='Contract ABI (Application Binary Interface)')),
                ('deployment_tx', models.CharField(blank=True, help_text='Transaction hash of deployment', max_length=255)),
                ('deployment_block', models.IntegerField(blank=True, help_text='Block height of deployment', null=True)),
                ('description', models.TextField(blank=True, help_text='Contract description')),
                ('ipfs_hash', models.CharField(blank=True, help_text='IPFS hash for contract metadata', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether contract is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(help_text='Name of function called', max_length=255)),
                ('parameters', models.JSONField(default=dict, help_text='Function parameters')),
                ('tx_hash', models.CharField(blank=True, help_text='Transaction hash', max_length=255)),
                ('block_height', models.IntegerField(blank=True, help_text='Block height', null=True)),
                ('success', models.BooleanField(default=False, help_text='Whether interaction was successful')),
                ('result', models.JSONField(default=dict, help_text='Interaction result')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_interactions', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='API.soliditycontract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(help_text='Evrmore asset name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Total quantity', max_digits=30)),
                ('units', models.IntegerField(default=0, help_text='Divisibility (0-8)')),
                ('reissuable', models.BooleanField(default=False, help_text='Whether asset can be reissued')),
                ('has_ipfs', models.BooleanField(default=False, help_text='Whether asset has IPFS metadata')),
                ('ipfs_hash', models.CharField(blank=True, help_text='IPFS hash', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='API.soliditycontract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='soliditycontract',
            index=models.Index(fields=['contract_address'], name='API_solidit_contrac_8d7e16_idx'),
        ),
        migrations.AddIndex(
            model_name='soliditycontract',
            index=models.Index(fields=['deployer', '-created_at'], name='API_solidit_deploye_a22ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinteraction',
            index=models.Index(fields=['contract', '-created_at'], name='API_contrac_contrac_95f3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinteraction',
            index=models.Index(fields=['user', '-created_at'], name='API_contrac_user_id_8ef028_idx'),
        ),
        migrations.AddIndex(
            model_name='contractasset',
            index=models.Index(fields=['asset_name'], name='API_contrac_asset_n_d8a439_idx'),
        ),
        migrations.AddIndex(
            model_name='contractasset',
            index=models.Index(fields=['contract', '-created_at'], name='API_contrac_contrac_786478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractasset',
            unique_together={('contract', 'asset_name')},
        ),
    ]
