# Generated by Django 6.0.1 on 2026-02-01 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('key_hash', models.CharField(help_text='SHA256 hash of the API key', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 characters of key for identification', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='API_apikey_key_has_0ed701_idx'), models.Index(fields=['user', '-created_at'], name='API_apikey_user_id_677dda_idx')],
            },
        ),
    ]
