# Generated by Django 6.0.1 on 2026-01-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('entropy', models.CharField(max_length=256)),
                ('passphrase', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
