# Generated by Django 6.0.1 on 2026-01-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
