# Generated by Django 6.0.1 on 2026-01-31 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('individual_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], db_index=True, max_length=4)),
                ('price', models.DecimalField(db_index=True, decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('token_offered', models.CharField(max_length=10)),
                ('preferred_token', models.CharField(max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='Listings.listingitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Listings.listingcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Listings.listingitem')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Listings.listingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('individual_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Listings.listingitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Listings.listingtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_token', models.CharField(max_length=10)),
                ('quote_token', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('base_token', 'quote_token')},
            },
        ),
        migrations.CreateModel(
            name='StopLossOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('trigger_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triggered', 'Triggered'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_loss_orders', to=settings.AUTH_USER_MODEL)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_loss_orders', to='Listings.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='OrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_executions', to=settings.AUTH_USER_MODEL)),
                ('buyer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_executions', to='Listings.limitorder')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_executions', to=settings.AUTH_USER_MODEL)),
                ('seller_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_executions', to='Listings.limitorder')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='Listings.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('executed', 'Executed'), ('failed', 'Failed')], default='executed', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to=settings.AUTH_USER_MODEL)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to='Listings.tradingpair')),
            ],
        ),
        migrations.AddField(
            model_name='limitorder',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_orders', to='Listings.tradingpair'),
        ),
    ]
