# Generated by Django 6.0.1 on 2026-02-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0003_alter_itemcategory_id_alter_limitorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity_available',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listingtransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=20),
        ),
    ]
