# Generated by Django 6.0.1 on 2026-02-01 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0004_alter_listing_quantity_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_index=True, decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('released', 'Released'), ('consumed', 'Consumed')], db_index=True, default='locked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('limit_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_lock', to='Listings.limitorder')),
                ('market_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_lock', to='Listings.marketorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_locks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
