# Generated by Django 6.0.1 on 2026-02-01 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0005_balancelock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingitem',
            name='is_nft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingitem',
            name='nft_image_ipfs_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for NFT image', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ipfs_cid', models.CharField(help_text='IPFS CID for NFT image', max_length=100)),
                ('token_id', models.CharField(db_index=True, help_text='Unique token ID for the NFT', max_length=100, unique=True)),
                ('contract_address', models.CharField(blank=True, help_text='Blockchain contract address if minted on-chain', max_length=100, null=True)),
                ('tx_hash', models.CharField(blank=True, help_text='Transaction hash for on-chain minting', max_length=100, null=True)),
                ('is_listed', models.BooleanField(default=False, help_text='Whether this NFT is currently listed for sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_nfts', to=settings.AUTH_USER_MODEL)),
                ('listing_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='Listings.listingitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nfts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
