# Generated by Django 6.0.1 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0006_listingitem_is_nft_listingitem_nft_image_ipfs_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='preferred_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='token_offered',
            field=models.CharField(max_length=255),
        ),
    ]