# Generated by Django 6.0.1 on 2026-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0007_atomic_swap_asset_identifiers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradingpair',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listing',
            name='network_mode',
            field=models.CharField(choices=[('testnet', 'Testnet'), ('mainnet', 'Mainnet')], db_index=True, default='testnet', max_length=10),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='network_mode',
            field=models.CharField(choices=[('testnet', 'Testnet'), ('mainnet', 'Mainnet')], db_index=True, default='testnet', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tradingpair',
            unique_together={('base_token', 'quote_token', 'network_mode')},
        ),
    ]
