# Generated by Django 6.0.1 on 2026-01-31 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Listings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('collateral_factor', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('liquidation_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('liquidation_penalty', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['token_symbol'],
            },
        ),
        migrations.CreateModel(
            name='InterestRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10, unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('optimal_utilization', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('slope_1', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('slope_2', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceFeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('oracle_address', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reputation_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_submissions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reputation_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestnetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DeFi Tome Testnet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('network_id', models.CharField(default='defitome-testnet-v1', max_length=50)),
                ('rpc_endpoint', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedRateBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10)),
                ('principal_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('fixed_rate_apr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_days', models.IntegerField(choices=[(30, '30 Days'), (90, '90 Days'), (180, '180 Days'), (365, '1 Year')])),
                ('maturity_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('expected_interest', models.DecimalField(decimal_places=8, max_digits=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('redeemed', 'Redeemed')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_rate_bonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10)),
                ('rate_type', models.CharField(choices=[('variable_supply', 'Variable Supply'), ('variable_borrow', 'Variable Borrow'), ('fixed_30d', 'Fixed 30 Day'), ('fixed_90d', 'Fixed 90 Day'), ('fixed_180d', 'Fixed 180 Day'), ('fixed_365d', 'Fixed 1 Year')], max_length=20)),
                ('rate_apr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utilization_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token_symbol', 'rate_type', '-timestamp'], name='DeFi_intere_token_s_c08737_idx')],
            },
        ),
        migrations.CreateModel(
            name='LendingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('total_deposits', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('total_borrows', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('total_reserves', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('last_accrual_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_rate_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='DeFi.interestrateconfig')),
            ],
            options={
                'ordering': ['token_symbol'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token_a_symbol', models.CharField(max_length=10)),
                ('token_b_symbol', models.CharField(max_length=10)),
                ('token_a_reserve', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('token_b_reserve', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_liquidity_tokens', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0.3, max_digits=5)),
                ('accumulated_token_a_fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('accumulated_token_b_fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('token_a_symbol', 'token_b_symbol')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('accrued_interest', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('collateral_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('liquidated', 'Liquidated')], default='active', max_length=20)),
                ('last_interest_update', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('liquidated_at', models.DateTimeField(blank=True, null=True)),
                ('collateral_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='DeFi.collateralasset')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='DeFi.lendingpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_seized', models.DecimalField(decimal_places=8, max_digits=30)),
                ('debt_covered', models.DecimalField(decimal_places=8, max_digits=30)),
                ('liquidation_penalty', models.DecimalField(decimal_places=8, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liquidator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidations_performed', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='DeFi.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('interest_paid', models.DecimalField(decimal_places=8, max_digits=30)),
                ('principal_paid', models.DecimalField(decimal_places=8, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='DeFi.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceFeedAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10)),
                ('aggregated_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('median_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('min_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('num_sources', models.IntegerField(default=0)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token_symbol', '-timestamp'], name='DeFi_pricef_token_s_ad9b8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwapOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_token', models.CharField(max_length=10)),
                ('offer_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('request_token', models.CharField(max_length=10)),
                ('request_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('escrow_id', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_swaps', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_offers', to='Listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='SwapEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_locked', models.BooleanField(default=False)),
                ('counterparty_locked', models.BooleanField(default=False)),
                ('initiator_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('counterparty_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('swap_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='DeFi.swapoffer')),
            ],
        ),
        migrations.CreateModel(
            name='P2PSwapTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_token', models.CharField(max_length=10)),
                ('initiator_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('counterparty_token', models.CharField(max_length=10)),
                ('counterparty_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_swaps_as_counterparty', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_swaps_as_initiator', to=settings.AUTH_USER_MODEL)),
                ('swap_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='DeFi.swapoffer')),
            ],
        ),
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_token', models.CharField(max_length=10)),
                ('to_token', models.CharField(max_length=10)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='DeFi.liquiditypool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VariableRateSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('accrued_interest', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('opening_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('last_rate_update', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_savings', to='DeFi.lendingpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_rate_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('accrued_interest', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('last_interest_update', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='DeFi.lendingpool')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pool')},
            },
        ),
        migrations.CreateModel(
            name='LiquidityPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidity_tokens', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unclaimed_token_a_fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unclaimed_token_b_fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='DeFi.liquiditypool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool')},
            },
        ),
        migrations.CreateModel(
            name='PriceFeedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_submissions', to='DeFi.pricefeedsource')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['token_symbol', '-timestamp'], name='DeFi_pricef_token_s_f05ae2_idx')],
            },
        ),
    ]
