# Generated by Django 6.0.1 on 2026-02-10 00:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeFi', '0003_contract_defiannouncement_deficonfig_defifaq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('toll_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage fee on transfers (0-100)', max_digits=5)),
                ('toll_address', models.CharField(help_text='Address receiving toll payments', max_length=100)),
                ('total_supply', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('is_reissuable', models.BooleanField(default=False)),
                ('units', models.IntegerField(default=8, help_text='Decimal places (0-8)')),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('total_toll_collected', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Total toll collected from transfers', max_digits=30)),
                ('transfer_count', models.IntegerField(default=0, help_text='Total number of transfers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='VaultCollateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('borrowed_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('collateral_ratio', models.DecimalField(decimal_places=2, default=Decimal('150'), help_text='Required collateral ratio (e.g., 150 = 150%)', max_digits=5)),
                ('liquidation_threshold', models.DecimalField(decimal_places=2, default=Decimal('120'), help_text='Liquidation threshold (e.g., 120 = 120%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_collateral', to=settings.AUTH_USER_MODEL)),
                ('vault_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_positions', to='DeFi.vaultasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultEscrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('toll_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Toll amount deducted on release', max_digits=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_vault_escrows', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_vault_escrows', to=settings.AUTH_USER_MODEL)),
                ('vault_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows', to='DeFi.vaultasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
