# Generated by Django 6.0.1 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeFi', '0004_vaultasset_vaultcollateral_vaultescrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapoffer',
            name='settlement_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='swapoffer',
            name='settlement_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapoffer',
            name='settlement_txid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='swapoffer',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('settling', 'Settling'),
                    ('accepted', 'Accepted'),
                    ('completed', 'Completed'),
                    ('rejected', 'Rejected'),
                    ('cancelled', 'Cancelled'),
                    ('expired', 'Expired'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]