# Generated by Django 6.0.1 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeFi', '0005_atomic_swap_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2pswaptransaction',
            name='counterparty_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='p2pswaptransaction',
            name='initiator_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='swapoffer',
            name='offer_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='swapoffer',
            name='request_token',
            field=models.CharField(max_length=255),
        ),
    ]