# Generated by Django 6.0.1 on 2026-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeFi', '0006_atomic_swap_asset_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapoffer',
            name='network_mode',
            field=models.CharField(choices=[('testnet', 'Testnet'), ('mainnet', 'Mainnet')], db_index=True, default='testnet', max_length=10),
        ),
    ]
