# Generated by Django 6.0.1 on 2026-08-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMetadataTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_address', models.CharField(max_length=128)),
                ('funding_address', models.CharField(blank=True, max_length=128)),
                ('main_asset', models.CharField(max_length=10)),
                ('tag_type', models.CharField(max_length=3)),
                ('revision', models.CharField(blank=True, max_length=7)),
                ('asset_name', models.CharField(db_index=True, max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('ipfs_cid', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('failed', 'Failed before broadcast'), ('broadcast_unknown', 'Broadcast outcome unknown')], default='pending', max_length=24)),
                ('error_message', models.TextField(blank=True)),
                ('signature_verified', models.BooleanField(null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_metadata_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='Media_addre_user_id_87d5cb_idx'),
                    models.Index(fields=['target_address', 'asset_name'], name='Media_addre_target__1526d4_idx'),
                ],
            },
        ),
    ]