# Generated by Django 6.0.1 on 2026-08-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='network_mode',
            field=models.CharField(choices=[('testnet', 'Testnet'), ('mainnet', 'Mainnet')], default='testnet', max_length=10),
        ),
    ]
