# Generated by Django 6.0.1 on 2026-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_userprofile_network_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rpc_endpoint_mode',
            field=models.CharField(choices=[('public', 'Public RPC'), ('local', 'Local Node RPC')], default='public', max_length=10),
        ),
    ]
